-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config21_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config21_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_3FFF9A2 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111100110100010";
    constant ap_const_lv26_3FFF9EF : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111100111101111";
    constant ap_const_lv26_3FFFA43 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101001000011";
    constant ap_const_lv26_1F7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111110111";
    constant ap_const_lv26_119 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100011001";
    constant ap_const_lv26_3FFFA80 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101010000000";
    constant ap_const_lv26_4A9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010010101001";
    constant ap_const_lv26_49C : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010010011100";
    constant ap_const_lv24_7B : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001111011";
    constant ap_const_lv25_D1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000011010001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv12_730 : STD_LOGIC_VECTOR (11 downto 0) := "011100110000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal trunc_ln708_4_reg_1058 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln703_22_fu_993_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_22_reg_1063 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_23_fu_999_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_23_reg_1068 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_27_fu_1011_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_27_reg_1073 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_30_fu_1033_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_30_reg_1078 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_25_fu_182_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln1118_28_fu_183_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_24_fu_184_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_27_fu_185_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_186_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_23_fu_187_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_22_fu_189_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_26_fu_191_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_29_fu_192_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_21_fu_193_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_186_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_21_fu_193_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln708_s_fu_765_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln1118_22_fu_189_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_23_fu_187_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_24_fu_184_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln_fu_824_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln1118_2_fu_836_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1118_28_fu_844_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1118_27_fu_832_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln1118_fu_848_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln1118_3_fu_864_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln1118_4_fu_876_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1118_29_fu_872_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln1118_30_fu_884_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln1118_fu_888_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln708_11_fu_894_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1118_25_fu_182_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_26_fu_191_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_27_fu_185_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_28_fu_183_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_29_fu_192_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln708_12_fu_973_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln708_3_fu_799_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_2_fu_784_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_750_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_fu_987_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_7_fu_913_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_5_fu_854_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_10_fu_958_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_9_fu_943_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_8_fu_928_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_26_fu_1005_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_1_fu_983_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln708_fu_775_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1118_31_fu_904_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_29_fu_1023_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_28_fu_1017_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln703_fu_1029_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_24_fu_1039_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_25_fu_1043_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_31_fu_1048_p2 : STD_LOGIC_VECTOR (15 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln703_22_reg_1063 <= add_ln703_22_fu_993_p2;
                add_ln703_23_reg_1068 <= add_ln703_23_fu_999_p2;
                add_ln703_27_reg_1073 <= add_ln703_27_fu_1011_p2;
                add_ln703_30_reg_1078 <= add_ln703_30_fu_1033_p2;
                trunc_ln708_4_reg_1058 <= mul_ln1118_24_fu_184_p2(25 downto 10);
            end if;
        end if;
    end process;
    add_ln1118_fu_848_p2 <= std_logic_vector(signed(sext_ln1118_28_fu_844_p1) + signed(sext_ln1118_27_fu_832_p1));
    add_ln703_22_fu_993_p2 <= std_logic_vector(unsigned(trunc_ln_fu_750_p4) + unsigned(add_ln703_fu_987_p2));
    add_ln703_23_fu_999_p2 <= std_logic_vector(unsigned(trunc_ln708_7_fu_913_p4) + unsigned(trunc_ln708_5_fu_854_p4));
    add_ln703_24_fu_1039_p2 <= std_logic_vector(unsigned(trunc_ln708_4_reg_1058) + unsigned(add_ln703_23_reg_1068));
    add_ln703_25_fu_1043_p2 <= std_logic_vector(unsigned(add_ln703_22_reg_1063) + unsigned(add_ln703_24_fu_1039_p2));
    add_ln703_26_fu_1005_p2 <= std_logic_vector(unsigned(trunc_ln708_10_fu_958_p4) + unsigned(trunc_ln708_9_fu_943_p4));
    add_ln703_27_fu_1011_p2 <= std_logic_vector(unsigned(trunc_ln708_8_fu_928_p4) + unsigned(add_ln703_26_fu_1005_p2));
    add_ln703_28_fu_1017_p2 <= std_logic_vector(signed(sext_ln708_1_fu_983_p1) + signed(sext_ln708_fu_775_p1));
    add_ln703_29_fu_1023_p2 <= std_logic_vector(signed(sext_ln1118_31_fu_904_p1) + signed(ap_const_lv12_730));
    add_ln703_30_fu_1033_p2 <= std_logic_vector(unsigned(add_ln703_28_fu_1017_p2) + unsigned(zext_ln703_fu_1029_p1));
    add_ln703_31_fu_1048_p2 <= std_logic_vector(unsigned(add_ln703_27_reg_1073) + unsigned(add_ln703_30_reg_1078));
    add_ln703_fu_987_p2 <= std_logic_vector(unsigned(trunc_ln708_3_fu_799_p4) + unsigned(trunc_ln708_2_fu_784_p4));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= std_logic_vector(unsigned(add_ln703_25_fu_1043_p2) + unsigned(add_ln703_31_fu_1048_p2));
    mul_ln1118_21_fu_193_p0 <= data_1_V_read;
    mul_ln1118_21_fu_193_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_21_fu_193_p0) * signed('0' &ap_const_lv25_D1))), 25));
    mul_ln1118_22_fu_189_p0 <= data_2_V_read;
    mul_ln1118_22_fu_189_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_22_fu_189_p0) * signed('0' &ap_const_lv26_4A9))), 26));
    mul_ln1118_23_fu_187_p0 <= data_3_V_read;
    mul_ln1118_23_fu_187_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_23_fu_187_p0) * signed(ap_const_lv26_3FFFA80))), 26));
    mul_ln1118_24_fu_184_p0 <= data_4_V_read;
    mul_ln1118_24_fu_184_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_24_fu_184_p0) * signed(ap_const_lv26_3FFFA43))), 26));
    mul_ln1118_25_fu_182_p0 <= data_7_V_read;
    mul_ln1118_25_fu_182_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_25_fu_182_p0) * signed(ap_const_lv26_3FFF9A2))), 26));
    mul_ln1118_26_fu_191_p0 <= data_8_V_read;
    mul_ln1118_26_fu_191_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_26_fu_191_p0) * signed('0' &ap_const_lv26_49C))), 26));
    mul_ln1118_27_fu_185_p0 <= data_9_V_read;
    mul_ln1118_27_fu_185_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_27_fu_185_p0) * signed('0' &ap_const_lv26_1F7))), 26));
    mul_ln1118_28_fu_183_p0 <= data_10_V_read;
    mul_ln1118_28_fu_183_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_28_fu_183_p0) * signed(ap_const_lv26_3FFF9EF))), 26));
    mul_ln1118_29_fu_192_p0 <= data_11_V_read;
    mul_ln1118_29_fu_192_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_29_fu_192_p0) * signed('0' &ap_const_lv24_7B))), 24));
    mul_ln1118_fu_186_p0 <= data_0_V_read;
    mul_ln1118_fu_186_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_fu_186_p0) * signed('0' &ap_const_lv26_119))), 26));
        sext_ln1118_27_fu_832_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_824_p3),26));

        sext_ln1118_28_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_2_fu_836_p3),26));

        sext_ln1118_29_fu_872_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_3_fu_864_p3),21));

        sext_ln1118_30_fu_884_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_4_fu_876_p3),21));

        sext_ln1118_31_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_11_fu_894_p4),12));

        sext_ln708_1_fu_983_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_12_fu_973_p4),16));

        sext_ln708_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_s_fu_765_p4),16));

    shl_ln1118_2_fu_836_p3 <= (data_5_V_read & ap_const_lv2_0);
    shl_ln1118_3_fu_864_p3 <= (data_6_V_read & ap_const_lv4_0);
    shl_ln1118_4_fu_876_p3 <= (data_6_V_read & ap_const_lv1_0);
    shl_ln_fu_824_p3 <= (data_5_V_read & ap_const_lv9_0);
    sub_ln1118_fu_888_p2 <= std_logic_vector(signed(sext_ln1118_29_fu_872_p1) - signed(sext_ln1118_30_fu_884_p1));
    trunc_ln708_10_fu_958_p4 <= mul_ln1118_28_fu_183_p2(25 downto 10);
    trunc_ln708_11_fu_894_p4 <= sub_ln1118_fu_888_p2(20 downto 10);
    trunc_ln708_12_fu_973_p4 <= mul_ln1118_29_fu_192_p2(23 downto 10);
    trunc_ln708_2_fu_784_p4 <= mul_ln1118_22_fu_189_p2(25 downto 10);
    trunc_ln708_3_fu_799_p4 <= mul_ln1118_23_fu_187_p2(25 downto 10);
    trunc_ln708_5_fu_854_p4 <= add_ln1118_fu_848_p2(25 downto 10);
    trunc_ln708_7_fu_913_p4 <= mul_ln1118_25_fu_182_p2(25 downto 10);
    trunc_ln708_8_fu_928_p4 <= mul_ln1118_26_fu_191_p2(25 downto 10);
    trunc_ln708_9_fu_943_p4 <= mul_ln1118_27_fu_185_p2(25 downto 10);
    trunc_ln708_s_fu_765_p4 <= mul_ln1118_21_fu_193_p2(24 downto 10);
    trunc_ln_fu_750_p4 <= mul_ln1118_fu_186_p2(25 downto 10);
    zext_ln703_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln703_29_fu_1023_p2),16));
end behav;
