-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity normalize_array_array_ap_fixed_12u_config15_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_V_data_0_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_0_V_empty_n : IN STD_LOGIC;
    data_V_data_0_V_read : OUT STD_LOGIC;
    data_V_data_1_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_1_V_empty_n : IN STD_LOGIC;
    data_V_data_1_V_read : OUT STD_LOGIC;
    data_V_data_2_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_2_V_empty_n : IN STD_LOGIC;
    data_V_data_2_V_read : OUT STD_LOGIC;
    data_V_data_3_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_3_V_empty_n : IN STD_LOGIC;
    data_V_data_3_V_read : OUT STD_LOGIC;
    data_V_data_4_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_4_V_empty_n : IN STD_LOGIC;
    data_V_data_4_V_read : OUT STD_LOGIC;
    data_V_data_5_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_5_V_empty_n : IN STD_LOGIC;
    data_V_data_5_V_read : OUT STD_LOGIC;
    data_V_data_6_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_6_V_empty_n : IN STD_LOGIC;
    data_V_data_6_V_read : OUT STD_LOGIC;
    data_V_data_7_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_7_V_empty_n : IN STD_LOGIC;
    data_V_data_7_V_read : OUT STD_LOGIC;
    data_V_data_8_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_8_V_empty_n : IN STD_LOGIC;
    data_V_data_8_V_read : OUT STD_LOGIC;
    data_V_data_9_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_9_V_empty_n : IN STD_LOGIC;
    data_V_data_9_V_read : OUT STD_LOGIC;
    data_V_data_10_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_10_V_empty_n : IN STD_LOGIC;
    data_V_data_10_V_read : OUT STD_LOGIC;
    data_V_data_11_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_11_V_empty_n : IN STD_LOGIC;
    data_V_data_11_V_read : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC;
    res_V_data_3_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_3_V_full_n : IN STD_LOGIC;
    res_V_data_3_V_write : OUT STD_LOGIC;
    res_V_data_4_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_4_V_full_n : IN STD_LOGIC;
    res_V_data_4_V_write : OUT STD_LOGIC;
    res_V_data_5_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_5_V_full_n : IN STD_LOGIC;
    res_V_data_5_V_write : OUT STD_LOGIC;
    res_V_data_6_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_6_V_full_n : IN STD_LOGIC;
    res_V_data_6_V_write : OUT STD_LOGIC;
    res_V_data_7_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_7_V_full_n : IN STD_LOGIC;
    res_V_data_7_V_write : OUT STD_LOGIC;
    res_V_data_8_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_8_V_full_n : IN STD_LOGIC;
    res_V_data_8_V_write : OUT STD_LOGIC;
    res_V_data_9_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_9_V_full_n : IN STD_LOGIC;
    res_V_data_9_V_write : OUT STD_LOGIC;
    res_V_data_10_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_10_V_full_n : IN STD_LOGIC;
    res_V_data_10_V_write : OUT STD_LOGIC;
    res_V_data_11_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_11_V_full_n : IN STD_LOGIC;
    res_V_data_11_V_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of normalize_array_array_ap_fixed_12u_config15_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_355 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001101010101";
    constant ap_const_lv26_231 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000110001";
    constant ap_const_lv26_292 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010010010";
    constant ap_const_lv26_468 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010001101000";
    constant ap_const_lv26_3F1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001111110001";
    constant ap_const_lv26_1AF : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110101111";
    constant ap_const_lv26_337 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001100110111";
    constant ap_const_lv26_3AA : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001110101010";
    constant ap_const_lv26_1F7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111110111";
    constant ap_const_lv26_3B4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001110110100";
    constant ap_const_lv26_30B : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001100001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_36B : STD_LOGIC_VECTOR (15 downto 0) := "0000001101101011";
    constant ap_const_lv16_FCE8 : STD_LOGIC_VECTOR (15 downto 0) := "1111110011101000";
    constant ap_const_lv16_FCA3 : STD_LOGIC_VECTOR (15 downto 0) := "1111110010100011";
    constant ap_const_lv16_FD45 : STD_LOGIC_VECTOR (15 downto 0) := "1111110101000101";
    constant ap_const_lv16_FCF3 : STD_LOGIC_VECTOR (15 downto 0) := "1111110011110011";
    constant ap_const_lv16_FDE9 : STD_LOGIC_VECTOR (15 downto 0) := "1111110111101001";
    constant ap_const_lv16_39A : STD_LOGIC_VECTOR (15 downto 0) := "0000001110011010";
    constant ap_const_lv16_FEAF : STD_LOGIC_VECTOR (15 downto 0) := "1111111010101111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_FDFD : STD_LOGIC_VECTOR (15 downto 0) := "1111110111111101";
    constant ap_const_lv16_FEA3 : STD_LOGIC_VECTOR (15 downto 0) := "1111111010100011";
    constant ap_const_lv16_FD19 : STD_LOGIC_VECTOR (15 downto 0) := "1111110100011001";
    constant ap_const_lv16_FFE1 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111100001";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal io_acc_block_signal_op4 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal io_acc_block_signal_op96 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal data_V_data_1_V_blk_n : STD_LOGIC;
    signal data_V_data_2_V_blk_n : STD_LOGIC;
    signal data_V_data_3_V_blk_n : STD_LOGIC;
    signal data_V_data_4_V_blk_n : STD_LOGIC;
    signal data_V_data_5_V_blk_n : STD_LOGIC;
    signal data_V_data_6_V_blk_n : STD_LOGIC;
    signal data_V_data_7_V_blk_n : STD_LOGIC;
    signal data_V_data_8_V_blk_n : STD_LOGIC;
    signal data_V_data_9_V_blk_n : STD_LOGIC;
    signal data_V_data_10_V_blk_n : STD_LOGIC;
    signal data_V_data_11_V_blk_n : STD_LOGIC;
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_3_V_blk_n : STD_LOGIC;
    signal res_V_data_4_V_blk_n : STD_LOGIC;
    signal res_V_data_5_V_blk_n : STD_LOGIC;
    signal res_V_data_6_V_blk_n : STD_LOGIC;
    signal res_V_data_7_V_blk_n : STD_LOGIC;
    signal res_V_data_8_V_blk_n : STD_LOGIC;
    signal res_V_data_9_V_blk_n : STD_LOGIC;
    signal res_V_data_10_V_blk_n : STD_LOGIC;
    signal res_V_data_11_V_blk_n : STD_LOGIC;
    signal tmp_data_V_0_reg_1429 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_1_reg_1434 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_2_reg_1439 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_3_reg_1444 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_4_reg_1449 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_5_reg_1454 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_6_reg_1459 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_7_reg_1464 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_8_reg_1469 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_8_reg_1469_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_9_reg_1475 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_10_reg_1480 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_1119_reg_1485 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_1490 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_s_reg_1495 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_1_reg_1500 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_2_reg_1505 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_3_reg_1510 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_4_reg_1515 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_5_reg_1520 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_6_reg_1525 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_8_reg_1530 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_9_reg_1535 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_10_reg_1540 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal mul_ln1118_12_fu_498_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_19_fu_499_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_18_fu_501_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_20_fu_502_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_16_fu_503_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_14_fu_504_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_17_fu_505_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_11_fu_506_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_13_fu_507_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_15_fu_508_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_509_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_509_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_11_fu_506_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_12_fu_498_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_13_fu_507_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_14_fu_504_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_15_fu_508_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_16_fu_503_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_17_fu_505_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_18_fu_501_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_19_fu_499_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_20_fu_502_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln_fu_1366_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln1118_1_fu_1377_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1118_18_fu_1373_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1118_19_fu_1384_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln1118_fu_1388_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln708_7_fu_1394_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= real_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_data_V_0_reg_1429 <= data_V_data_0_V_dout;
                tmp_data_V_10_reg_1480 <= data_V_data_10_V_dout;
                tmp_data_V_1119_reg_1485 <= data_V_data_11_V_dout;
                tmp_data_V_1_reg_1434 <= data_V_data_1_V_dout;
                tmp_data_V_2_reg_1439 <= data_V_data_2_V_dout;
                tmp_data_V_3_reg_1444 <= data_V_data_3_V_dout;
                tmp_data_V_4_reg_1449 <= data_V_data_4_V_dout;
                tmp_data_V_5_reg_1454 <= data_V_data_5_V_dout;
                tmp_data_V_6_reg_1459 <= data_V_data_6_V_dout;
                tmp_data_V_7_reg_1464 <= data_V_data_7_V_dout;
                tmp_data_V_8_reg_1469 <= data_V_data_8_V_dout;
                tmp_data_V_8_reg_1469_pp0_iter1_reg <= tmp_data_V_8_reg_1469;
                tmp_data_V_9_reg_1475 <= data_V_data_9_V_dout;
                trunc_ln708_10_reg_1540 <= mul_ln1118_20_fu_502_p2(25 downto 10);
                trunc_ln708_1_reg_1500 <= mul_ln1118_12_fu_498_p2(25 downto 10);
                trunc_ln708_2_reg_1505 <= mul_ln1118_13_fu_507_p2(25 downto 10);
                trunc_ln708_3_reg_1510 <= mul_ln1118_14_fu_504_p2(25 downto 10);
                trunc_ln708_4_reg_1515 <= mul_ln1118_15_fu_508_p2(25 downto 10);
                trunc_ln708_5_reg_1520 <= mul_ln1118_16_fu_503_p2(25 downto 10);
                trunc_ln708_6_reg_1525 <= mul_ln1118_17_fu_505_p2(25 downto 10);
                trunc_ln708_8_reg_1530 <= mul_ln1118_18_fu_501_p2(25 downto 10);
                trunc_ln708_9_reg_1535 <= mul_ln1118_19_fu_499_p2(25 downto 10);
                trunc_ln708_s_reg_1495 <= mul_ln1118_11_fu_506_p2(25 downto 10);
                trunc_ln_reg_1490 <= mul_ln1118_fu_509_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(real_start, ap_done_reg, ap_enable_reg_pp0_iter2, io_acc_block_signal_op4, io_acc_block_signal_op96)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((real_start = ap_const_logic_1) and ((io_acc_block_signal_op4 = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) or ((io_acc_block_signal_op96 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(real_start, ap_done_reg, ap_enable_reg_pp0_iter2, io_acc_block_signal_op4, io_acc_block_signal_op96)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((real_start = ap_const_logic_1) and ((io_acc_block_signal_op4 = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) or ((io_acc_block_signal_op96 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(real_start, ap_done_reg, ap_enable_reg_pp0_iter2, io_acc_block_signal_op4, io_acc_block_signal_op96)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((real_start = ap_const_logic_1) and ((io_acc_block_signal_op4 = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) or ((io_acc_block_signal_op96 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(real_start, ap_done_reg, io_acc_block_signal_op4)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((io_acc_block_signal_op4 = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(io_acc_block_signal_op96)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (io_acc_block_signal_op96 = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= real_start;

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((real_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    ap_reset_idle_pp0_assign_proc : process(real_start, ap_idle_pp0_0to1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_0_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_0_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_0_V_blk_n <= data_V_data_0_V_empty_n;
        else 
            data_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_10_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_10_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_10_V_blk_n <= data_V_data_10_V_empty_n;
        else 
            data_V_data_10_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_10_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_10_V_read <= ap_const_logic_1;
        else 
            data_V_data_10_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_11_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_11_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_11_V_blk_n <= data_V_data_11_V_empty_n;
        else 
            data_V_data_11_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_11_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_11_V_read <= ap_const_logic_1;
        else 
            data_V_data_11_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_1_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_1_V_blk_n <= data_V_data_1_V_empty_n;
        else 
            data_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_2_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_2_V_blk_n <= data_V_data_2_V_empty_n;
        else 
            data_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_3_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_3_V_blk_n <= data_V_data_3_V_empty_n;
        else 
            data_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_3_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_4_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_4_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_4_V_blk_n <= data_V_data_4_V_empty_n;
        else 
            data_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_4_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_4_V_read <= ap_const_logic_1;
        else 
            data_V_data_4_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_5_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_5_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_5_V_blk_n <= data_V_data_5_V_empty_n;
        else 
            data_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_5_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_5_V_read <= ap_const_logic_1;
        else 
            data_V_data_5_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_6_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_6_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_6_V_blk_n <= data_V_data_6_V_empty_n;
        else 
            data_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_6_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_6_V_read <= ap_const_logic_1;
        else 
            data_V_data_6_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_7_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_7_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_7_V_blk_n <= data_V_data_7_V_empty_n;
        else 
            data_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_7_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_7_V_read <= ap_const_logic_1;
        else 
            data_V_data_7_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_8_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_8_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_8_V_blk_n <= data_V_data_8_V_empty_n;
        else 
            data_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_8_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_8_V_read <= ap_const_logic_1;
        else 
            data_V_data_8_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_9_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_9_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_9_V_blk_n <= data_V_data_9_V_empty_n;
        else 
            data_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_9_V_read_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_9_V_read <= ap_const_logic_1;
        else 
            data_V_data_9_V_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(real_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((real_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op4 <= (data_V_data_9_V_empty_n and data_V_data_8_V_empty_n and data_V_data_7_V_empty_n and data_V_data_6_V_empty_n and data_V_data_5_V_empty_n and data_V_data_4_V_empty_n and data_V_data_3_V_empty_n and data_V_data_2_V_empty_n and data_V_data_1_V_empty_n and data_V_data_11_V_empty_n and data_V_data_10_V_empty_n and data_V_data_0_V_empty_n);
    io_acc_block_signal_op96 <= (res_V_data_9_V_full_n and res_V_data_8_V_full_n and res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_11_V_full_n and res_V_data_10_V_full_n and res_V_data_0_V_full_n);
    mul_ln1118_11_fu_506_p0 <= tmp_data_V_1_reg_1434;
    mul_ln1118_11_fu_506_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_11_fu_506_p0) * signed('0' &ap_const_lv26_3AA))), 26));
    mul_ln1118_12_fu_498_p0 <= tmp_data_V_2_reg_1439;
    mul_ln1118_12_fu_498_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_12_fu_498_p0) * signed('0' &ap_const_lv26_355))), 26));
    mul_ln1118_13_fu_507_p0 <= tmp_data_V_3_reg_1444;
    mul_ln1118_13_fu_507_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_13_fu_507_p0) * signed('0' &ap_const_lv26_1F7))), 26));
    mul_ln1118_14_fu_504_p0 <= tmp_data_V_4_reg_1449;
    mul_ln1118_14_fu_504_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_14_fu_504_p0) * signed('0' &ap_const_lv26_1AF))), 26));
    mul_ln1118_15_fu_508_p0 <= tmp_data_V_5_reg_1454;
    mul_ln1118_15_fu_508_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_15_fu_508_p0) * signed('0' &ap_const_lv26_3B4))), 26));
    mul_ln1118_16_fu_503_p0 <= tmp_data_V_6_reg_1459;
    mul_ln1118_16_fu_503_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_16_fu_503_p0) * signed('0' &ap_const_lv26_3F1))), 26));
    mul_ln1118_17_fu_505_p0 <= tmp_data_V_7_reg_1464;
    mul_ln1118_17_fu_505_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_17_fu_505_p0) * signed('0' &ap_const_lv26_337))), 26));
    mul_ln1118_18_fu_501_p0 <= tmp_data_V_9_reg_1475;
    mul_ln1118_18_fu_501_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_18_fu_501_p0) * signed('0' &ap_const_lv26_292))), 26));
    mul_ln1118_19_fu_499_p0 <= tmp_data_V_10_reg_1480;
    mul_ln1118_19_fu_499_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_19_fu_499_p0) * signed('0' &ap_const_lv26_231))), 26));
    mul_ln1118_20_fu_502_p0 <= tmp_data_V_1119_reg_1485;
    mul_ln1118_20_fu_502_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_20_fu_502_p0) * signed('0' &ap_const_lv26_468))), 26));
    mul_ln1118_fu_509_p0 <= tmp_data_V_0_reg_1429;
    mul_ln1118_fu_509_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_fu_509_p0) * signed('0' &ap_const_lv26_30B))), 26));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_0_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_0_V_din <= std_logic_vector(unsigned(trunc_ln_reg_1490) + unsigned(ap_const_lv16_36B));

    res_V_data_0_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_10_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_10_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_10_V_blk_n <= res_V_data_10_V_full_n;
        else 
            res_V_data_10_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_10_V_din <= std_logic_vector(unsigned(trunc_ln708_9_reg_1535) + unsigned(ap_const_lv16_FD19));

    res_V_data_10_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_10_V_write <= ap_const_logic_1;
        else 
            res_V_data_10_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_11_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_11_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_11_V_blk_n <= res_V_data_11_V_full_n;
        else 
            res_V_data_11_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_11_V_din <= std_logic_vector(unsigned(trunc_ln708_10_reg_1540) + unsigned(ap_const_lv16_FFE1));

    res_V_data_11_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_11_V_write <= ap_const_logic_1;
        else 
            res_V_data_11_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_1_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_1_V_din <= std_logic_vector(unsigned(trunc_ln708_s_reg_1495) + unsigned(ap_const_lv16_FCE8));

    res_V_data_1_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_2_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_2_V_din <= std_logic_vector(unsigned(trunc_ln708_1_reg_1500) + unsigned(ap_const_lv16_FCA3));

    res_V_data_2_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_3_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_3_V_blk_n <= res_V_data_3_V_full_n;
        else 
            res_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_3_V_din <= std_logic_vector(unsigned(trunc_ln708_2_reg_1505) + unsigned(ap_const_lv16_FD45));

    res_V_data_3_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_4_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_4_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_4_V_blk_n <= res_V_data_4_V_full_n;
        else 
            res_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_4_V_din <= std_logic_vector(unsigned(trunc_ln708_3_reg_1510) + unsigned(ap_const_lv16_FCF3));

    res_V_data_4_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_4_V_write <= ap_const_logic_1;
        else 
            res_V_data_4_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_5_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_5_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_5_V_blk_n <= res_V_data_5_V_full_n;
        else 
            res_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_5_V_din <= std_logic_vector(unsigned(trunc_ln708_4_reg_1515) + unsigned(ap_const_lv16_FDE9));

    res_V_data_5_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_5_V_write <= ap_const_logic_1;
        else 
            res_V_data_5_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_6_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_6_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_6_V_blk_n <= res_V_data_6_V_full_n;
        else 
            res_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_6_V_din <= std_logic_vector(unsigned(trunc_ln708_5_reg_1520) + unsigned(ap_const_lv16_39A));

    res_V_data_6_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_6_V_write <= ap_const_logic_1;
        else 
            res_V_data_6_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_7_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_7_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_7_V_blk_n <= res_V_data_7_V_full_n;
        else 
            res_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_7_V_din <= std_logic_vector(unsigned(trunc_ln708_6_reg_1525) + unsigned(ap_const_lv16_FEAF));

    res_V_data_7_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_7_V_write <= ap_const_logic_1;
        else 
            res_V_data_7_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_8_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_8_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_8_V_blk_n <= res_V_data_8_V_full_n;
        else 
            res_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_8_V_din <= std_logic_vector(unsigned(trunc_ln708_7_fu_1394_p4) + unsigned(ap_const_lv16_FDFD));

    res_V_data_8_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_8_V_write <= ap_const_logic_1;
        else 
            res_V_data_8_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_9_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, res_V_data_9_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            res_V_data_9_V_blk_n <= res_V_data_9_V_full_n;
        else 
            res_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_9_V_din <= std_logic_vector(unsigned(trunc_ln708_8_reg_1530) + unsigned(ap_const_lv16_FEA3));

    res_V_data_9_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_9_V_write <= ap_const_logic_1;
        else 
            res_V_data_9_V_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln1118_18_fu_1373_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_1366_p3),26));

        sext_ln1118_19_fu_1384_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_1_fu_1377_p3),26));

    shl_ln1118_1_fu_1377_p3 <= (tmp_data_V_8_reg_1469_pp0_iter1_reg & ap_const_lv1_0);
    shl_ln_fu_1366_p3 <= (tmp_data_V_8_reg_1469_pp0_iter1_reg & ap_const_lv9_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln1118_fu_1388_p2 <= std_logic_vector(signed(sext_ln1118_18_fu_1373_p1) - signed(sext_ln1118_19_fu_1384_p1));
    trunc_ln708_7_fu_1394_p4 <= sub_ln1118_fu_1388_p2(25 downto 10);
end behav;
